import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="top-4 flex items-center gap-20 bg-white/90 px-4 ">
          <Image
            src="/taniti-logo.png"
            alt="Taniti Island Logo"
            width={100}
            height={20}
            priority
          />
          <nav className="flex items-center gap-2">
            <a
              href="/"
              className="text-sm font-medium text-zinc-950 hover:underline"
            >
              Getting Here
            </a>
            |
            <a
              href="/about"
              className="text-sm font-medium text-zinc-950 hover:underline"
            >
              Where to Stay
            </a>
            |
            <a
              href="/about"
              className="text-sm font-medium text-zinc-950 hover:underline"
            >
              Getting Around
            </a>
            |
            <a
              href="/about"
              className="text-sm font-medium text-zinc-950 hover:underline"
            >
              Entertainment
            </a>
            |
            <a
              href="/about"
              className="text-sm font-medium text-zinc-950 hover:underline"
            >
              Sightseeing
            </a>
          </nav>
        </div>
        <hr className="mt-1 border-zinc-200" />
        <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans bg-black">
          {children}
        </div>
        <hr className="mt-1 border-zinc-200" />
        <div className="mb-4 mt-2 flex justify-center text-sm text-zinc-500">
          &copy; 2026 Taniti Island. All rights reserved.
        </div>
      </body>
    </html>
  );
}
