import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 border-b border-gray-200 bg-white px-8 py-4 shadow-sm">
          <div className="mx-auto flex max-w-7xl items-center justify-between">
            <a href="/" className="flex items-center">
              <Image
                src="/images/taniti-logo.png"
                alt="Taniti Island Logo"
                width={100}
                height={40}
                priority
              />
            </a>
            <nav className="flex items-center gap-1">
              <a
                href="/"
                className="px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:text-gray-900"
              >
                Home
              </a>
              <span className="text-gray-300">|</span>
              <a
                href="/getting-here"
                className="px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:text-gray-900"
              >
                Getting Here
              </a>
              <span className="text-gray-300">|</span>
              <a
                href="/where-to-stay"
                className="px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:text-gray-900"
              >
                Where to Stay
              </a>
              <span className="text-gray-300">|</span>
              <a
                href="/getting-around"
                className="px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:text-gray-900"
              >
                Getting Around
              </a>
              <span className="text-gray-300">|</span>
              <a
                href="/entertainment"
                className="px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:text-gray-900"
              >
                Entertainment
              </a>
              <span className="text-gray-300">|</span>
              <a
                href="/sightseeing"
                className="px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:text-gray-900"
              >
                Sightseeing
              </a>
            </nav>
          </div>
        </header>
        <div className="bg-white">
          {children}
        </div>
        <footer className="border-t border-gray-200 bg-white py-6">
          <div className="mx-auto flex max-w-7xl justify-center px-8">
            <p className="text-sm text-gray-500">
              &copy; 2026 Taniti Island. All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
